<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    
    <modelVersion>4.0.0</modelVersion>
    
    <!-- C:\Users\desab\dev\apache-camel\camel-testing-ega -->

    <groupId>com.desabi.guide.jdk.best.practices</groupId>
    <artifactId>jdk-best-practices</artifactId>
    <version>1.0-SNAPSHOT</version>
    <!--<packaging>jar</packaging>-->    

    <name>jdk-best-practices</name>
    <description>Java 25 Best Practices Guide</description>

    <properties>
        <java.version>25</java.version>

        <!-- Maven Compiler settings -->
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <!-- Ensures both source and target compatibility -->
		<!-- You could technically just use this property and omit source + target, but many projects
		     keep all three for clarity and backward compatibility with older Maven plugins.
		     but many projects keep all three for clarity and backward compatibility with older
		     Maven plugins.-->
		<maven.compiler.release>${java.version}</maven.compiler.release>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <build>
        <plugins>
            <!-- Compiler plugin: tells Maven which Java version to use -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>${java.version}</release> <!--release 25 flag -->
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>